{
  pkgs,
  appearance,
  config,
  ...
}:
let
  cp = appearance.catppuccin.${appearance.catppuccinVariant};

  # 壁纸目录(与 sway 共用 assets/wallpapers), 供 hyprpaper preload 与随机脚本使用
  wallpaperDir = ../../../assets/wallpapers;
  wallpapers = builtins.attrNames (builtins.readDir wallpaperDir);

  # 随机壁纸 (对应 sway 的 wallpaper_random)
  hyprWallpaperRandom = pkgs.writeShellScriptBin "hypr-wallpaper-random" ''
    #!/bin/sh
    LIST=$(grep '^preload' ~/.config/hypr/hyprpaper.conf | sed 's/^preload = //')
    COUNT=$(echo "$LIST" | wc -l)
    [ "$COUNT" -lt 1 ] && exit 0
    N=$(( (RANDOM % COUNT) + 1 ))
    WALL=$(echo "$LIST" | sed -n "''${N}p")
    MONITOR=$(${pkgs.hyprland}/bin/hyprctl monitors -j | ${pkgs.jq}/bin/jq -r '.[0].name')
    ${pkgs.hyprland}/bin/hyprctl hyprpaper wallpaper "$MONITOR,$WALL"
  '';

  # 默认壁纸 (对应 sway 的 default_wall)
  hyprWallpaperDefault = pkgs.writeShellScriptBin "hypr-wallpaper-default" ''
    #!/bin/sh
    MONITOR=$(${pkgs.hyprland}/bin/hyprctl monitors -j | ${pkgs.jq}/bin/jq -r '.[0].name')
    ${pkgs.hyprland}/bin/hyprctl hyprpaper wallpaper "$MONITOR,~/.config/hypr/wallpaper.png"
  '';

  # hyprpaper: preload 全部壁纸 (默认壁纸 + assets/wallpapers 目录), 首屏用默认
  hyprpaperConf = ''
    preload = ~/.config/hypr/wallpaper.png
    ${builtins.concatStringsSep "\n" (map (w: "preload = ~/.config/hypr/wallpapers/${w}") wallpapers)}
    wallpaper = ,~/.config/hypr/wallpaper.png
  '';

  # caelestia-shell 配置: 禁用自带 idle (用 swayidle), 终端/文件管理器/播放器对齐现有应用
  caelestiaConf = ''
    {
      "appearance": {
        "transparency": {
          "enabled": false
        },
        "anim": {
          "durations": {
            "scale": 0.75
          }
        }
      },
      "general": {
        "apps": {
          "terminal": ["kitty"],
          "audio": ["pavucontrol"],
          "playback": ["mpv"],
          "explorer": ["nemo"]
        },
        "idle": {
          "timeouts": []
        }
      },
      "paths": {
        "wallpaperDir": "${config.home.homeDirectory}/.config/hypr/wallpapers"
      }
    }
  '';

  # 工作区数字 1-10 (10 映射到 0)
  wsKeys = [
    "1"
    "2"
    "3"
    "4"
    "5"
    "6"
    "7"
    "8"
    "9"
    "0"
  ];

  # 方向映射 (sway HJKL + 方向键 → hl.dsp direction)
  dirKeys = [
    {
      key = "H";
      dir = "left";
    }
    {
      key = "J";
      dir = "down";
    }
    {
      key = "K";
      dir = "up";
    }
    {
      key = "L";
      dir = "right";
    }
    {
      key = "left";
      dir = "left";
    }
    {
      key = "down";
      dir = "down";
    }
    {
      key = "up";
      dir = "up";
    }
    {
      key = "right";
      dir = "right";
    }
  ];

  resizeKeys = [
    {
      key = "H";
      x = "-10";
      y = "0";
    }
    {
      key = "J";
      x = "0";
      y = "10";
    }
    {
      key = "K";
      x = "0";
      y = "-10";
    }
    {
      key = "L";
      x = "10";
      y = "0";
    }
    {
      key = "left";
      x = "-10";
      y = "0";
    }
    {
      key = "down";
      x = "0";
      y = "10";
    }
    {
      key = "up";
      x = "0";
      y = "-10";
    }
    {
      key = "right";
      x = "10";
      y = "0";
    }
  ];

  # Hyprland 0.56+ 的 Lua 配置格式 (.conf 将在 0.57 移除)。
  # 键位与 sway 对齐 (见 home/wm/sway/config.nix)。
  # 注意: hyprctl dispatch 在 0.56 只接受 Lua 表达式, 绑定一律用原生 hl.dsp.*。
  hyprlandLua = ''
    -- generated by nix — Hyprland 独立第二套 WM (Lua 配置)
    -- 启动: ly 登录管理器选择 Hyprland; 键位与 sway 对齐。

    -- 环境 (只探测 Intel 卡: 不打开 nvidia DRM 节点, 保证 eGPU 可热卸载)
    hl.env("AQ_DRM_DEVICES", "/dev/dri/card0")
    hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
    hl.env("XDG_SESSION_DESKTOP", "Hyprland")
    hl.env("XDG_SESSION_TYPE", "wayland")
    -- Electron 应用 (QQ/微信) 强制 Wayland 原生: XWayland 在 scale 1.25 下
    -- 渲染低分辨率再放大, 字体模糊; Wayland 模式正确感知分数缩放
    hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
    -- 覆盖 sway 模块全局的 QT_SCALE_FACTOR=1 (Hyprland 下应自动/1.25)
    hl.env("QT_SCALE_FACTOR", "auto")

    -- 显示器 (内屏与 sway 一致 scale 1.25, 其他输出自动)
    hl.monitor({
        output   = "eDP-1",
        mode     = "preferred",
        position = "auto",
        scale    = "1.25",
    })
    hl.monitor({
        output   = "",
        mode     = "preferred",
        position = "auto",
        scale    = "auto",
    })

    -- 自启动 (caelestia-shell 桌面 shell / 壁纸 / 输入法 / 剪贴板 / 待机锁屏)
    hl.on("hyprland.start", function()
        hl.exec_cmd("caelestia shell -d")
        hl.exec_cmd("hyprpaper")
        hl.exec_cmd("fcitx5 -d")
        hl.exec_cmd("wl-paste --watch cliphist store")
        hl.exec_cmd("xrdb -merge ~/.Xresources")
        hl.exec_cmd("swayidle -w timeout 600 'caelestia shell lock lock' before-sleep 'caelestia shell lock lock'")
    end)

    -- 布局 / 装饰 / 输入
    hl.config({
        general = {
            gaps_in  = 4,
            gaps_out = 8,
            border_size = 2,
            col = {
                active_border   = "0xff${cp.color4}",
                inactive_border = "0xff${cp.color0}",
            },
            layout = "dwindle",
        },
        decoration = {
            rounding = 8,
            blur = {
                enabled = true,
                size    = 4,
                passes  = 1,
            },
            shadow = {
                enabled      = true,
                range        = 20,
                render_power = 2,
            },
        },
        animations = {
            enabled = true,
        },
        input = {
            kb_layout  = "us",
            kb_options = "caps:escape",
            follow_mouse = 1,
            touchpad = {
                natural_scroll = true,
                tap_to_click   = true,
            },
        },
        dwindle = {
            preserve_split = true,
        },
    })

    -- 动画曲线与动画
    hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
    hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
    hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
    hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })
    hl.animation({ leaf = "border",     enabled = true, speed = 5.39,  bezier = "easeOutQuint" })
    hl.animation({ leaf = "windows",    enabled = true, speed = 4.79,  spring = "easy" })
    hl.animation({ leaf = "windowsIn",  enabled = true, speed = 4.1,   spring = "easy" })
    hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49,  bezier = "quick" })
    hl.animation({ leaf = "fade",       enabled = true, speed = 3.03,  bezier = "quick" })
    hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94,  bezier = "almostLinear", style = "fade" })

    -- 浮窗规则 (对齐 sway 的 for_window)
    hl.window_rule({ name = "float-termfloat",   match = { class = "termfloat" },   float = true })
    hl.window_rule({ name = "size-termfloat",    match = { class = "termfloat" },   size = "960 540" })
    hl.window_rule({ name = "float-mpv",         match = { class = "mpv" },         float = true })
    hl.window_rule({ name = "size-mpv",          match = { class = "mpv" },         size = "960 540" })
    hl.window_rule({ name = "float-nemo",        match = { class = "nemo" },        float = true })
    hl.window_rule({ name = "size-nemo",         match = { class = "nemo" },        size = "960 540" })
    hl.window_rule({ name = "float-utils",       match = { class = "pavucontrol|blueberry|nm-connection-editor|org.pulseaudio.pavucontrol" }, float = true })
    hl.window_rule({ name = "center-utils",      match = { class = "pavucontrol|blueberry|nm-connection-editor|org.pulseaudio.pavucontrol" }, center = true })
    hl.window_rule({ name = "float-flameshot",   match = { class = "flameshot" },   float = true, border_size = 0 })
    hl.window_rule({ name = "float-wemeet",      match = { class = "wemeetapp" },   float = true })
    hl.window_rule({ name = "float-feishu",      match = { class = "feishu" },      float = true })

    -- ---------- 键位 (对齐 sway, home/wm/sway/config.nix) ----------
    local mainMod = "SUPER"

    -- 终端
    hl.bind(mainMod .. " + Return",      hl.dsp.exec_cmd("kitty"))
    hl.bind(mainMod .. " + SHIFT + Return", hl.dsp.exec_cmd("kitty --class=termfloat"))

    -- 工作区: 上一个/下一个
    hl.bind(mainMod .. " + slash",  hl.dsp.focus({ workspace = "-1" }))
    hl.bind(mainMod .. " + period", hl.dsp.focus({ workspace = "+1" }))
    hl.bind(mainMod .. " + comma",  hl.dsp.focus({ workspace = "-1" }))

    -- 快速启动应用
    hl.bind("ALT + SHIFT + S", hl.dsp.exec_cmd("splayer"))
    hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("firefox"))
    hl.bind(mainMod .. " + SHIFT + Y", hl.dsp.exec_cmd("qutebrowser"))
    hl.bind(mainMod .. " + SHIFT + X", hl.dsp.exec_cmd("caelestia shell lock lock"))
    hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("Telegram"))
    hl.bind(mainMod .. " + SHIFT + Q", function()
        hl.dispatch(hl.dsp.focus({ workspace = "QQ" }))
        hl.dispatch(hl.dsp.exec_cmd("qq"))
    end)
    hl.bind("ALT + SHIFT + Q", hl.dsp.focus({ workspace = "QQ" }))
    hl.bind("ALT + SHIFT + T", hl.dsp.focus({ workspace = "TG" }))
    hl.bind("ALT + SHIFT + W", hl.dsp.focus({ workspace = "WC" }))
    hl.bind("ALT + SHIFT + B", hl.dsp.focus({ workspace = "Ff" }))
    hl.bind("ALT + SHIFT + Y", hl.dsp.focus({ workspace = "Qb" }))
    hl.bind("ALT + SHIFT + V", hl.dsp.focus({ workspace = "VT" }))
    hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("vesktop"))

    -- 截图
    hl.bind(mainMod .. " + bracketleft",  hl.dsp.exec_cmd('grimshot --notify savecopy anything ~/Pictures/$(date "+%Y-%m-%d"T"%H_%M_%S").png'))
    hl.bind(mainMod .. " + bracketright", hl.dsp.exec_cmd("grimshot --notify copy anything"))
    hl.bind(mainMod .. " + A",            hl.dsp.exec_cmd('grimshot --notify savecopy anything ~/Pictures/$(date "+%Y-%m-%d"T"%H_%M_%S").png'))
    hl.bind("print",                      hl.dsp.exec_cmd("flameshot gui"))

    -- 壁纸 (hypr 版; dynamic/video 壁纸为 sway 专属, 未移植)
    hl.bind(mainMod .. " + SHIFT + W",        hl.dsp.exec_cmd("${hyprWallpaperRandom}/bin/hypr-wallpaper-random"))
    hl.bind(mainMod .. " + CTRL + SHIFT + W", hl.dsp.exec_cmd("${hyprWallpaperDefault}/bin/hypr-wallpaper-default"))

    -- 窗口操作
    hl.bind(mainMod .. " + Q",             hl.dsp.window.close())
    hl.bind(mainMod .. " + SHIFT + space", hl.dsp.window.float())
    hl.bind(mainMod .. " + minus",         hl.dsp.window.move({ workspace = "special:scratchpad" }))
    hl.bind(mainMod .. " + equal",         hl.dsp.workspace.toggle_special("scratchpad"))

    -- 启动器 / 电源菜单改用 caelestia 内置 (launcher / session 菜单)
    -- 剪贴板保持 rofi: caelestia 1.0.0 无内置剪贴板模块
    hl.bind(mainMod .. " + Z", hl.dsp.global("caelestia:launcher"), { release = true })
    hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("pkill rofi || ~/.config/rofi/clipboard.sh"))
    hl.bind(mainMod .. " + SHIFT + P", hl.dsp.global("caelestia:session"))

    -- 焦点移动 (HJKL + 方向键)
    ${builtins.concatStringsSep "\n" (
      map (d: ''
        hl.bind(mainMod .. " + ${d.key}", hl.dsp.focus({ direction = "${d.dir}" }))
      '') dirKeys
    )}

    -- 移动窗口 (HJKL + 方向键)
    ${builtins.concatStringsSep "\n" (
      map (d: ''
        hl.bind(mainMod .. " + SHIFT + ${d.key}", hl.dsp.window.move({ direction = "${d.dir}" }))
      '') dirKeys
    )}

    -- 工作区 1-10
    ${builtins.concatStringsSep "\n" (
      map (n: ''
        hl.bind(mainMod .. " + ${n}", hl.dsp.focus({ workspace = ${n} }))
      '') wsKeys
    )}

    -- 移动窗口到工作区
    ${builtins.concatStringsSep "\n" (
      map (n: ''
        hl.bind(mainMod .. " + SHIFT + ${n}", hl.dsp.window.move({ workspace = ${n} }))
      '') wsKeys
    )}

    -- 移动并跟随 (sway: $mod+Ctrl+1..0; window.move 默认跟随)
    ${builtins.concatStringsSep "\n" (
      map (n: ''
        hl.bind(mainMod .. " + CTRL + ${n}", hl.dsp.window.move({ workspace = ${n} }))
      '') wsKeys
    )}

    -- 布局: 全屏 / gaps 开关
    hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
    hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("bash -c 'hyprctl keyword general:gaps_in 0; hyprctl keyword general:gaps_out 0'"))
    hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("bash -c 'hyprctl keyword general:gaps_in 4; hyprctl keyword general:gaps_out 8'"))

    -- 快速 resize (Shift+Ctrl+HJKL / 方向键; relative=true 按窗口尺寸百分比)
    ${builtins.concatStringsSep "\n" (
      map (r: ''
        hl.bind("SHIFT + CTRL + ${r.key}", hl.dsp.window.resize({ x = ${r.x}, y = ${r.y}, relative = true }))
      '') resizeKeys
    )}

    -- 重载 / 退出
    hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprctl reload"))
    hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exit())

    -- caelestia 全局快捷键 (caelestia 仅注册名字, 键位由 Hyprland 绑定)
    -- launcher 必须 release 触发 (caelestia 在松开时才 toggle, press 只设内部标记)
    -- launcher 在 SUPER+Z, session 菜单在 SUPER+SHIFT+P (见上方 rofi 段)
    hl.bind(mainMod .. " + D",         hl.dsp.global("caelestia:dashboard"))
    hl.bind(mainMod .. " + B",         hl.dsp.global("caelestia:sidebar"))
    hl.bind(mainMod .. " + U",         hl.dsp.global("caelestia:utilities"))
    hl.bind(mainMod .. " + N",         hl.dsp.global("caelestia:nexus"))
    hl.bind(mainMod .. " + grave",     hl.dsp.global("caelestia:showall"))

    -- 音量 / 亮度 / 媒体
    hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 5"))
    hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 5"))
    hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t"))
    hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pamixer --default-source -t"))
    hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"))
    hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))
    hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("mpc -q toggle"))
    hl.bind("XF86AudioNext", hl.dsp.exec_cmd("mpc -q next"))
    hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("mpc -q prev"))
  '';
in
{
  home.file = {
    ".config/hypr/hyprland.lua".text = hyprlandLua;
    ".config/hypr/hyprpaper.conf".text = hyprpaperConf;
    ".config/hypr/wallpaper.png".source = ../../../assets/wallpapers/default.png;
    ".config/hypr/wallpapers".source = wallpaperDir;
    # shell.json 不用 home.file (store 只读链接) — caelestia autosave 会写回该文件,
    # 只读链接导致每次启动弹"保存配置失败"(Failed to write ... Permission denied)。
    # 改由 home.activation 复制为可写文件 (声明式模板, 运行时修改在 rebuild 后重置)。
  };

  # caelestia 配置必须可写 (autosave 写回); 不用 home.file 链接, 复制为真实文件
  home.activation.caelestiaWritableConfig = config.lib.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "$HOME/.config/caelestia"
    # 先删旧链接 (hm 历史部署的 store 只读链接), cp 才落到真实文件
    rm -f "$HOME/.config/caelestia/shell.json"
    cp -f ${pkgs.writeText "caelestia-shell.json" caelestiaConf} "$HOME/.config/caelestia/shell.json"
    chmod 644 "$HOME/.config/caelestia/shell.json"
  '';
}
