{
  pkgs,
  lib,
  appearance,
  config,
  ...
}:
let
  h = appearance.toHex;
  variants = builtins.attrNames appearance.catppuccin; # latte frappe macchiato mocha
  themes = appearance.catppuccin;
  currentDir = "${config.home.homeDirectory}/.config/catppuccin/current";
  themesDir = "${config.home.homeDirectory}/.config/catppuccin/themes";
  stateFile = "${config.home.homeDirectory}/.cache/catppuccin-current";

  # 每个主题的四个运行时文件(切换时 cp 到 current/ 并热应用)
  kittyColors = t: ''
    foreground           ${h t.fg}
    background           ${h t.bg}
    selection_foreground #000000
    selection_background ${h t.color8}
    url_color            ${h t.color4}
    cursor               ${h t.color4}

    color0  ${h t.color0}
    color1  ${h t.color1}
    color2  ${h t.color2}
    color3  ${h t.color3}
    color4  ${h t.color4}
    color5  ${h t.color5}
    color6  ${h t.color6}
    color7  ${h t.color7}
    color8  ${h t.color8}
    color9  ${h t.color9}
    color10 ${h t.color10}
    color11 ${h t.color11}
    color12 ${h t.color12}
    color13 ${h t.color13}
    color14 ${h t.color14}
    color15 ${h t.color15}
  '';

  swayColors = t: ''
    client.focused          ${h t.color4} ${h t.color4} #ffffff
    client.unfocused        ${h t.bg} ${h t.color0} #888888
    client.focused_inactive ${h t.bg} ${h t.color0} #888888
    client.placeholder      ${h t.bg} ${h t.color0} #888888
    client.urgent           ${h t.color1} ${h t.color1} #ffffff
    client.background       ${h t.bg}
  '';

  swayApply = t: ''
    #!/bin/sh
    # generated by nix — apply window colors to the running sway
    ${pkgs.sway}/bin/swaymsg 'client.focused ${h t.color4} ${h t.color4} #ffffff'
    ${pkgs.sway}/bin/swaymsg 'client.unfocused ${h t.bg} ${h t.color0} #888888'
    ${pkgs.sway}/bin/swaymsg 'client.focused_inactive ${h t.bg} ${h t.color0} #888888'
    ${pkgs.sway}/bin/swaymsg 'client.placeholder ${h t.bg} ${h t.color0} #888888'
    ${pkgs.sway}/bin/swaymsg 'client.urgent ${h t.color1} ${h t.color1} #ffffff'
    ${pkgs.sway}/bin/swaymsg 'client.background ${h t.bg}'
  '';

  waybarColors = t: ''
    /* generated by nix — catppuccin ${t} */
    @define-color wall_bg     ${h themes.${t}.bg};
    @define-color wall_bg_alt ${h themes.${t}.color0};
    @define-color wall_fg     ${h themes.${t}.fg};
    @define-color wall_fg_dim ${h themes.${t}.color7};
    @define-color wall_red    ${h themes.${t}.color1};
    @define-color wall_green  ${h themes.${t}.color2};
    @define-color wall_yellow ${h themes.${t}.color3};
    @define-color wall_blue   ${h themes.${t}.color4};
    @define-color wall_purple ${h themes.${t}.color5};
    @define-color wall_cyan   ${h themes.${t}.color6};
  '';

  # 生成 4 主题 × 4 文件: ~/.config/catppuccin/themes/<variant>/...
  themeFiles = lib.mkMerge (
    map (v: {
      "catppuccin/themes/${v}/kitty-colors.conf".text = kittyColors themes.${v};
      "catppuccin/themes/${v}/sway-colors.conf".text = swayColors themes.${v};
      "catppuccin/themes/${v}/sway-apply.sh".text = swayApply themes.${v};
      "catppuccin/themes/${v}/waybar-colors.css".text = waybarColors v;
    }) variants
  );

  variantsStr = builtins.concatStringsSep " " variants;

  themeApply = pkgs.writeShellScriptBin "theme-apply" ''
    #!/bin/sh
    # 切换 catppuccin 主题: theme-apply [variant]  |  theme-apply (自动下一个)
    VARIANTS="${variantsStr}"
    THEMES_DIR="${themesDir}"
    CURRENT_DIR="${currentDir}"
    STATE="${stateFile}"
    CURRENT=$(cat "$STATE" 2>/dev/null || echo mocha)

    NEXT="$1"
    if [ -z "$NEXT" ]; then
      found=0
      for v in $VARIANTS; do
        if [ "$found" = "1" ]; then NEXT="$v"; break; fi
        [ "$v" = "$CURRENT" ] && found=1
      done
      [ -z "$NEXT" ] && NEXT=$(echo "$VARIANTS" | cut -d' ' -f1)
    fi
    if [ ! -d "$THEMES_DIR/$NEXT" ]; then
      ${pkgs.libnotify}/bin/notify-send "主题切换" "未知主题: $NEXT"
      exit 1
    fi

    mkdir -p "$CURRENT_DIR"
    for f in kitty-colors.conf sway-colors.conf sway-apply.sh waybar-colors.css; do
      cp "$THEMES_DIR/$NEXT/$f" "$CURRENT_DIR/$f"
      # cp 保留 store 源的 444 只读权限, 恢复可写以便下次覆盖
      chmod 644 "$CURRENT_DIR/$f"
    done
    echo "$NEXT" > "$STATE"

    # 热应用: kitty(运行中的实例) + waybar(重载 CSS) + sway(边框色)
    KITTY_SOCK="$XDG_RUNTIME_DIR/kitty-listen.sock"
    if [ -S "$KITTY_SOCK" ]; then
      kitty @ --to "unix:$KITTY_SOCK" set-colors "$CURRENT_DIR/kitty-colors.conf" 2>/dev/null
    fi
    ${pkgs.procps}/bin/pkill -RTMIN+5 -f '.waybar-wrapped' 2>/dev/null
    sh "$CURRENT_DIR/sway-apply.sh" 2>/dev/null

    ${pkgs.libnotify}/bin/notify-send "Catppuccin" "已切换到 $NEXT"
  '';

  themeTimerToggle = pkgs.writeShellScriptBin "theme-timer-toggle" ''
    #!/bin/sh
    # 开启/停止每 2 小时自动轮换主题
    systemctl --user daemon-reload 2>/dev/null
    if systemctl --user is-active theme-rotator.timer >/dev/null 2>&1; then
      systemctl --user stop theme-rotator.timer
      systemctl --user disable theme-rotator.timer >/dev/null 2>&1 || true
      ${pkgs.libnotify}/bin/notify-send "主题轮换" "已停止(每2小时自动切换)"
    else
      systemctl --user enable --now theme-rotator.timer >/dev/null 2>&1 || true
      ${pkgs.libnotify}/bin/notify-send "主题轮换" "已开启(每2小时自动切换)"
    fi
  '';
in
{
  home.packages = [
    themeApply
    themeTimerToggle
  ];

  xdg.configFile = themeFiles;

  # 登录时初始化 current/(kitty/sway/waybar 的 include/@import 依赖),并保证 state 有初值
  systemd.user.services.theme-init = {
    Unit = {
      Description = "Initialize catppuccin current theme";
      After = [ "graphical-session.target" ];
    };
    Install.WantedBy = [ "graphical-session.target" ];
    Service = {
      Type = "oneshot";
      ExecStart = "${themeApply}/bin/theme-apply mocha";
      RemainAfterExit = true;
    };
  };

  # 每 2 小时自动轮换(timer 由 home.file 生成, 不随 hm systemd 模块自动启用;
  # waybar 右键 theme-timer-toggle 开启/停止)
  systemd.user.services.theme-rotator = {
    Unit = {
      Description = "Rotate catppuccin theme every 2 hours";
    };
    Service = {
      Type = "oneshot";
      ExecStart = "${themeApply}/bin/theme-apply";
    };
  };
  home.file.".config/systemd/user/theme-rotator.timer" = {
    text = ''
      [Unit]
      Description=Rotate catppuccin theme every 2 hours

      [Timer]
      OnBootSec=2h
      OnUnitActiveSec=2h
      Unit=theme-rotator.service

      [Install]
      WantedBy=timers.target
    '';
  };
}
